# Generated by Django 4.2.13 on 2024-06-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='instype',
            new_name='instrument_type',
        ),
    ]
